services:
  # Backend API service
  - type: web
    name: webscraper-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/models

  # Frontend service
  - type: web
    name: webscraper-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
